services:
  postgres:
    image: postgres:16-alpine
    container_name: conectaclinica-db
    restart: always
    environment:
      POSTGRES_DB: conectaclinica
      POSTGRES_USER: clinica_user
      POSTGRES_PASSWORD: clinica_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinica_user -d conectaclinica"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: conectaclinica-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@conectaclinica.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: