# Configuracoes do Banco de Dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/conectaclinica}
spring.datasource.username=${DB_USERNAME:clinica_user}
spring.datasource.password=${DB_PASSWORD:clinica_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# Dialeto para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracoes de Documentacao e Aplicacao
springdoc.override-with-generic-response=false
spring.application.name=ConectaClinica

# Configuracoes de Seguranca / JWT
api.security.token.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971}
api.security.token.expiration=${JWT_EXPIRATION:28800000}

# ===================================================================
# CONFIGURACOES DE E-MAIL (SPRING MAIL)
# ===================================================================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=seu_usuario_Mailtrap
spring.mail.password=sua_senha_Mailtrap

# Propriedades adicionais do JavaMail (necessarias para conexoes SMTP seguras)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true